[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32c3"
ESP_IDF_VERSION = "v5.3"
ESP_IDF_TOOLS_INSTALL_DIR = "global"
CRATE_CC_NO_DEFAULTS = "1"
ESP_IDF_GLOB_0_BASE = { value = "", relative = true }
ESP_IDF_GLOB_0_0 = "partitions.csv"
